services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - $PORT:5000
    container_name: portfolio
    restart: unless-stopped
    command: npm run start
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - POSTGRES_USER=$POSTGRES_USER 
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_URL=$POSTGRES_URL
      - GOTIFY_TOKEN=$GOTIFY_TOKEN